In [44]:
import numpy as np
from itertools import product

In [18]:
# 1(a)
arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr = arr[::-1]
print(arr)


[1 2 3 4 5]
[5 4 3 2 1]


In [19]:
# 1(b)
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
print(array1)

flat_arr_1 = array1.flatten()
print(flat_arr_1)

flat_arr_2 = array1.ravel()
print(flat_arr_2)


[[1 2 3]
 [2 4 5]
 [1 2 3]]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [20]:
# 1(c)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

same = np.array_equal(arr1, arr2)
print(same)

True


In [25]:
# 1(d)
x=np.array([1,2,3,4,5,1,2,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

print("x:",x)
x_cnt=np.bincount(x)
print("Most frequent element in x:", np.argmax(x_cnt))

print("y:",y)
y_cnt=np.bincount(y)
print("Most frequent element in y:", np.argmax(y_cnt))


x: [1 2 3 4 5 1 2 1 1]
Most frequent element in x: 1
y: [1 1 1 2 3 4 2 4 3 3]
Most frequent element in y: 1


In [29]:
# 1(e)
gfg = np.matrix('[4,1,9 ; 12,3,1 ; 4,5,6]')
print(gfg)

total_sum = gfg.sum()
row_sum = gfg.sum(axis=1)
col_sum = gfg.sum(axis=0)
print("Total sum:", total_sum)
print("Row sum:", row_sum)
print("Column sum:", col_sum)



[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Total sum: 45
Row sum: [[14]
 [16]
 [15]]
Column sum: [[20  9 16]]


In [35]:
# 1(f)
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print(n_array)

dig_sum = np.trace(n_array)
print("Diagonal sum:", dig_sum)

e_val = np.linalg.eigvals(n_array)
print("Eigen values:", e_val)

e_vec = np.linalg.eig(n_array)[1]
print("Eigen vectors:", e_vec)

inv_mat = np.linalg.inv(n_array)
print("Inverse matrix: ", inv_mat)

det = np.linalg.det(n_array)
print("Determinant:", det)

[[55 25 15]
 [30 44  2]
 [11 45 77]]
Diagonal sum: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse matrix:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [41]:
# 1(g)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

multi1 = np.dot(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("Matrix multiplication:", multi1)
print("Covariance matrix:", cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

multi2 = np.dot(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())
print("Matrix multiplication:", multi2)
print("Covariance matrix:", cov2)


Matrix multiplication: [[16 19]
 [26 31]]
Covariance matrix: [[0.66666667 1.        ]
 [1.         1.66666667]]
Matrix multiplication: [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix: [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [45]:
# 1(h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
outer = np.outer(x.flatten(), y.flatten())
cartesian = np.array([np.concatenate([a, b]) for a, b in product(x, y)])

print("Inner product:", inner)
print("Outer product:", outer)
print("Cartesian product:", cartesian)

Inner product: [[17 52]
 [13 62]]
Outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product: [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]
