In [2]:
import numpy as np

In [9]:
#1(a)
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(array)

#(i)
abs_array = np.abs(array)
print(abs_array)

#(ii)
flat = array.flatten()
percentile_flat = np.percentile(flat, [25, 50, 75])
print(percentile_flat)

percentile_col = np.percentile(array, [25, 50, 75], axis=0)
print(percentile_col)

percentile_row = np.percentile(array, [25, 50, 75], axis=1)
print(percentile_row)

#(iii)
mean_flat = np.mean(flat)
median_flat = np.median(flat)
sd_flat = np.std(flat)
print(mean_flat, median_flat, sd_flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
sd_col = np.std(array, axis=0)
print(mean_col, median_col, sd_col)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
sd_row = np.std(array, axis=1)
print(mean_row, median_row, sd_row)


[[ 1 -2  3]
 [-4  5 -6]]
[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
[ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


In [13]:
# 2(b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(a)

floor_a = np.floor(a)
ceil_a = np.ceil(a)
turncated_a = np.trunc(a)
rounded_a = np.round(a)

print(floor_a)
print(ceil_a)
print(turncated_a)
print(rounded_a)

[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]
