In [3]:
import numpy as np

In [ ]:
# 3(a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(array)

# (i)
sorted_array = np.sort(array)
print(sorted_array)

# (ii)
indices = np.argsort(array)
print(indices)

# (iii)
smallest_elements = np.partition(array, 4)[:4]
print(smallest_elements)

# (iv)
largest_elements = np.partition(array, -5)[-5:]
print(largest_elements)

[ 10  52  62  16  16  54 453]
[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[16 10 16 52]
[ 16  52  62  54 453]


In [9]:
# 3(b)
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(arr)

# (i)
integers = arr[arr == arr.astype(int)]
print(integers)

# (ii)
floats = arr[arr != arr.astype(int)]
print(floats)


[1.  1.2 2.2 2.  3.  2. ]
[1. 2. 3. 2.]
[1.2 2.2]
